spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: lmn
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        hbm2ddl:
          auto: update  

