spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: lmn
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
      #naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        hbm2ddl:
          auto: none  

